version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:3.0.1
    links:
      - zookeeper
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$DOCKER_HOST_IP:9092
      - KAFKA_ADVERTISED_HOST_NAME=$DOCKER_HOST_IP
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"